### ISSUE TITLE
Оформление научно-справочного апарата

### ISSUE THREAD

**Issue by iarkhanhelsky** [bsutex/bsustyle#13]
* При использовании сведений из источника с большим количеством
страниц студент должен указать в том месте работы, где дается ссылка на этот
источник, номера страниц, иллюстраций, таблиц, на которые дается ссылка в
работе. Например: «[14, с. 26, таблица 2]» (здесь 14 - номер источника в списке
использованной литературы, 26 - номер страницы, 2 - номер таблицы), или
«[18, с. 44]» (здесь 18 - номер источника в списке использованной литературы,
44 - номер страницы).

* Ссылки на источники в тексте работы осуществляются путем приведения
номера в соответствии со списком использованной литературы. Номер
источника по списку заключается в квадратные скобки

**Comment by hannarud** [comment]
* Решается при помощи `\cite[с. 26, таблица 2]{Bibliography_item_name_here}`

* Решается при помощи использования BibTeX и `\cite[optional_text]{Bibliography_item_name_here}`. Правда, пока у меня BibTeX не работает
